"""Add company table

Revision ID: 22468f2f0ea1
Revises: 2579589cce8c
Create Date: 2025-10-26 02:43:33.912648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22468f2f0ea1'
down_revision: Union[str, Sequence[str], None] = '2579589cce8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('consolidated',
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('treatment', sa.Text(), nullable=False),
    sa.Column('incomplete', sa.Integer(), nullable=True),
    sa.Column('incomplete_dta', sa.Integer(), nullable=True),
    sa.Column('admitted', sa.Integer(), nullable=True),
    sa.Column('new_periods', sa.Integer(), nullable=True),
    sa.Column('nonadmitted', sa.Integer(), nullable=True),
    sa.Column('incomplete_prev', sa.Integer(), nullable=True),
    sa.Column('incomplete_diff', sa.Integer(), nullable=True),
    sa.Column('incomplete_expected', sa.Integer(), nullable=True),
    sa.Column('untreated', sa.Integer(), nullable=True),
    sa.Column('admitted_prev', sa.Integer(), nullable=True),
    sa.Column('new_periods_prev', sa.Integer(), nullable=True),
    sa.Column('nonadmitted_prev', sa.Integer(), nullable=True),
    sa.Column('treated', sa.Integer(), nullable=True),
    sa.Column('treated_prev', sa.Integer(), nullable=True),
    sa.Column('wait_diff', sa.Integer(), nullable=True),
    sa.Column('wait_gte_18', sa.Integer(), nullable=True),
    sa.Column('wait_lt_18', sa.Integer(), nullable=True),
    sa.Column('wait_sum', sa.Integer(), nullable=True),
    sa.Column('wait_pct_lt_18', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider'], ['providers.provider_code'], ),
    sa.PrimaryKeyConstraint('period', 'provider', 'treatment')
    )
    op.add_column('providers', sa.Column('region_name', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('type', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('subtype', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('provider_code', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('provider_name', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('Reporting_date', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('Average_score', sa.REAL(), nullable=True))
    op.add_column('providers', sa.Column('Likely_range_of_average_score', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('Segment', sa.REAL(), nullable=True))
    op.add_column('providers', sa.Column('Trust_in_financial_deficit', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('Rank', sa.REAL(), nullable=True))
    op.add_column('providers', sa.Column('Likely_range_of_rank', sa.Text(), nullable=True))
    op.drop_index(op.f('providers_trust_code_uindex'), table_name='providers')
    op.drop_column('providers', 'pct_18wks_elective')
    op.drop_column('providers', 'pct_52wks_elective')
    op.drop_column('providers', 'aande_4hour')
    op.drop_column('providers', 'cancer_faster_diagnose')
    op.drop_column('providers', 'cancer_62_day')
    op.drop_column('providers', 'diagnostic_proportion')
    op.drop_column('providers', 'trust_name')
    op.drop_column('providers', 'trust_code')
    op.drop_column('providers', 'aande_12hour')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('aande_12hour', sa.TEXT(), nullable=True))
    op.add_column('providers', sa.Column('trust_code', sa.TEXT(), nullable=True))
    op.add_column('providers', sa.Column('trust_name', sa.TEXT(), nullable=True))
    op.add_column('providers', sa.Column('diagnostic_proportion', sa.REAL(), nullable=True))
    op.add_column('providers', sa.Column('cancer_62_day', sa.REAL(), nullable=True))
    op.add_column('providers', sa.Column('cancer_faster_diagnose', sa.REAL(), nullable=True))
    op.add_column('providers', sa.Column('aande_4hour', sa.REAL(), nullable=True))
    op.add_column('providers', sa.Column('pct_52wks_elective', sa.REAL(), nullable=True))
    op.add_column('providers', sa.Column('pct_18wks_elective', sa.REAL(), nullable=True))
    op.create_index(op.f('providers_trust_code_uindex'), 'providers', ['trust_code'], unique=1)
    op.drop_column('providers', 'Likely_range_of_rank')
    op.drop_column('providers', 'Rank')
    op.drop_column('providers', 'Trust_in_financial_deficit')
    op.drop_column('providers', 'Segment')
    op.drop_column('providers', 'Likely_range_of_average_score')
    op.drop_column('providers', 'Average_score')
    op.drop_column('providers', 'Reporting_date')
    op.drop_column('providers', 'provider_name')
    op.drop_column('providers', 'provider_code')
    op.drop_column('providers', 'subtype')
    op.drop_column('providers', 'type')
    op.drop_column('providers', 'region_name')
    op.create_table('incomplete_with_dta',
    sa.Column('period', sa.TEXT(), nullable=False),
    sa.Column('region_code', sa.TEXT(), nullable=True),
    sa.Column('provider_code', sa.TEXT(), nullable=False),
    sa.Column('provider_name', sa.TEXT(), nullable=True),
    sa.Column('treatment_function_code', sa.TEXT(), nullable=False),
    sa.Column('treatment_function', sa.TEXT(), nullable=True),
    sa.Column('data_type', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('Total_number_of_incomplete_pathways_with_a_decision_to_admit_for_treatment', sa.REAL(), nullable=True),
    sa.Column('pct_of_incomplete_pathways_with_a_decision_to_admit_for_treatment', sa.REAL(), nullable=True),
    sa.CheckConstraint('length(period) = 10'),
    sa.PrimaryKeyConstraint('period', 'provider_code', 'treatment_function_code', 'data_type')
    )
    op.create_table('admitted',
    sa.Column('period', sa.TEXT(), nullable=False),
    sa.Column('region_code', sa.TEXT(), nullable=True),
    sa.Column('provider_code', sa.TEXT(), nullable=False),
    sa.Column('provider_name', sa.TEXT(), nullable=True),
    sa.Column('treatment_function_code', sa.TEXT(), nullable=False),
    sa.Column('treatment_function', sa.TEXT(), nullable=True),
    sa.Column('data_type', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('Patients_with_unknown_clock_start_date', sa.REAL(), nullable=True),
    sa.Column('Total_number_of_completed_pathways_all', sa.REAL(), nullable=True),
    sa.Column('Total_number_of_completed_pathways_with_a_known_clock_start', sa.REAL(), nullable=True),
    sa.Column('Average_median_waiting_time_in_weeks', sa.REAL(), nullable=True),
    sa.Column('col_95th_percentile_waiting_time_in_weeks', sa.REAL(), nullable=True),
    sa.Column('Total_52_plus_weeks', sa.REAL(), nullable=True),
    sa.Column('Total_78_plus_weeks', sa.REAL(), nullable=True),
    sa.Column('Total_65_plus_weeks', sa.REAL(), nullable=True),
    sa.CheckConstraint('length(period) = 10'),
    sa.PrimaryKeyConstraint('period', 'provider_code', 'treatment_function_code', 'data_type')
    )
    op.create_table('new_periods',
    sa.Column('period', sa.TEXT(), nullable=False),
    sa.Column('region_code', sa.TEXT(), nullable=True),
    sa.Column('provider_code', sa.TEXT(), nullable=False),
    sa.Column('provider_name', sa.TEXT(), nullable=True),
    sa.Column('treatment_function_code', sa.TEXT(), nullable=False),
    sa.Column('treatment_function', sa.TEXT(), nullable=True),
    sa.Column('data_type', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('Number_of_new_RTT_clock_starts_during_the_month', sa.REAL(), nullable=True),
    sa.CheckConstraint('length(period) = 10'),
    sa.PrimaryKeyConstraint('period', 'provider_code', 'treatment_function_code', 'data_type')
    )
    op.create_table('nonadmitted',
    sa.Column('period', sa.TEXT(), nullable=False),
    sa.Column('region_code', sa.TEXT(), nullable=True),
    sa.Column('provider_code', sa.TEXT(), nullable=False),
    sa.Column('provider_name', sa.TEXT(), nullable=True),
    sa.Column('treatment_function_code', sa.TEXT(), nullable=False),
    sa.Column('treatment_function', sa.TEXT(), nullable=True),
    sa.Column('data_type', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('Patients_with_unknown_clock_start_date', sa.REAL(), nullable=True),
    sa.Column('Total_number_of_completed_pathways_all', sa.REAL(), nullable=True),
    sa.Column('Total_number_of_completed_pathways_with_a_known_clock_start', sa.REAL(), nullable=True),
    sa.Column('Average_median_waiting_time_in_weeks', sa.REAL(), nullable=True),
    sa.Column('col_95th_percentile_waiting_time_in_weeks', sa.REAL(), nullable=True),
    sa.Column('Total_52_plus_weeks', sa.REAL(), nullable=True),
    sa.Column('Total_78_plus_weeks', sa.REAL(), nullable=True),
    sa.Column('Total_65_plus_weeks', sa.REAL(), nullable=True),
    sa.CheckConstraint('length(period) = 10'),
    sa.PrimaryKeyConstraint('period', 'provider_code', 'treatment_function_code', 'data_type')
    )
    op.create_table('incomplete',
    sa.Column('period', sa.TEXT(), nullable=False),
    sa.Column('region_code', sa.TEXT(), nullable=True),
    sa.Column('provider_code', sa.TEXT(), nullable=False),
    sa.Column('provider_name', sa.TEXT(), nullable=True),
    sa.Column('treatment_function_code', sa.TEXT(), nullable=False),
    sa.Column('treatment_function', sa.TEXT(), nullable=True),
    sa.Column('data_type', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('Total_number_of_incomplete_pathways', sa.REAL(), nullable=True),
    sa.Column('Total_within_18_weeks', sa.REAL(), nullable=True),
    sa.Column('pct_within_18_weeks', sa.REAL(), nullable=True),
    sa.Column('Average_median_waiting_time_in_weeks', sa.REAL(), nullable=True),
    sa.Column('col_92nd_percentile_waiting_time_in_weeks', sa.REAL(), nullable=True),
    sa.CheckConstraint('length(period) = 10'),
    sa.PrimaryKeyConstraint('period', 'provider_code', 'treatment_function_code', 'data_type')
    )
    op.drop_table('consolidated')
    op.drop_table('v_consolidated')
    # ### end Alembic commands ###
