"""rename treated to completed

Revision ID: 0cfd72612a8d
Revises: 8594878d7504
Create Date: 2025-12-09 13:34:44.078538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cfd72612a8d'
down_revision: Union[str, Sequence[str], None] = '8594878d7504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consolidated', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_treatable', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_prev', sa.Integer(), nullable=True))
        batch_op.drop_column('treated')
        batch_op.drop_column('treated_prev')

    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Region', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Trust_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Trust_subtype', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Trust_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Trust_name', sa.Text(), nullable=True))
        batch_op.alter_column('Average_score',
               existing_type=sa.FLOAT(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('Segment',
               existing_type=sa.BIGINT(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('Rank',
               existing_type=sa.BIGINT(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.create_index('provider_Trust_code_uindex', ['Trust_code'], unique=True)
        batch_op.drop_column('provider')
        batch_op.drop_column('region_name')
        batch_op.drop_column('type')
        batch_op.drop_column('subtype')
        batch_op.drop_column('provider_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('subtype', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('region_name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.TEXT(), nullable=True))
        batch_op.drop_index('provider_Trust_code_uindex')
        batch_op.alter_column('Rank',
               existing_type=sa.REAL(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('Segment',
               existing_type=sa.REAL(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('Average_score',
               existing_type=sa.REAL(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('Trust_name')
        batch_op.drop_column('Trust_code')
        batch_op.drop_column('Trust_subtype')
        batch_op.drop_column('Trust_type')
        batch_op.drop_column('Region')

    with op.batch_alter_table('consolidated', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treated_prev', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('treated', sa.INTEGER(), nullable=True))
        batch_op.drop_column('completed_prev')
        batch_op.drop_column('completed')
        batch_op.drop_column('total_treatable')

    # ### end Alembic commands ###
