"""initial schemajhbugefe

Revision ID: 16f1e71a125c
Revises: 896b6cc92d2f
Create Date: 2025-12-07 15:13:10.593270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f1e71a125c'
down_revision: Union[str, Sequence[str], None] = '896b6cc92d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('non_admitted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wait_lt_18', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wait_gte_18', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wait_pct_lt_18', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wait_pct_gte_18', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qa_wait_diff', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qa_wait_sum', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qa_diff_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qa_diff_total_all', sa.Integer(), nullable=True))
        batch_op.drop_column('diff_total_all')
        batch_op.drop_column('wait_sum')
        batch_op.drop_column('diff_total')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('non_admitted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diff_total', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('wait_sum', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('diff_total_all', sa.INTEGER(), nullable=True))
        batch_op.drop_column('qa_diff_total_all')
        batch_op.drop_column('qa_diff_total')
        batch_op.drop_column('qa_wait_sum')
        batch_op.drop_column('qa_wait_diff')
        batch_op.drop_column('wait_pct_gte_18')
        batch_op.drop_column('wait_pct_lt_18')
        batch_op.drop_column('wait_gte_18')
        batch_op.drop_column('wait_lt_18')

    # ### end Alembic commands ###
