"""initial schema

Revision ID: 6bcd6014e3b3
Revises:
Create Date: 2025-10-26 03:16:50.897755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcd6014e3b3'
down_revision: Union[str, Sequence[str], None] = '8aadb59c0c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('Region', sa.Text(), nullable=True),
    sa.Column('Trust_type', sa.Text(), nullable=True),
    sa.Column('Trust_subtype', sa.Text(), nullable=True),
    sa.Column('Trust_code', sa.Text(), nullable=False),
    sa.Column('Trust_name', sa.Text(), nullable=True),
    sa.Column('Reporting_date', sa.Text(), nullable=True),
    sa.Column('Average_score', sa.REAL(), nullable=True),
    sa.Column('Likely_range_of_average_score', sa.Text(), nullable=True),
    sa.Column('Segment', sa.REAL(), nullable=True),
    sa.Column('Trust_in_financial_deficit', sa.Text(), nullable=True),
    sa.Column('Rank', sa.REAL(), nullable=True),
    sa.Column('Likely_range_of_rank', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Trust_code')
    )
    op.create_index('provider_Trust_code_uindex', 'provider', ['Trust_code'], unique=True)
    op.create_table('providers',
    sa.Column('region_name', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('subtype', sa.Text(), nullable=True),
    sa.Column('provider_code', sa.Text(), nullable=True),
    sa.Column('provider_name', sa.Text(), nullable=True),
    sa.Column('Reporting_date', sa.Text(), nullable=True),
    sa.Column('Average_score', sa.REAL(), nullable=True),
    sa.Column('Likely_range_of_average_score', sa.Text(), nullable=True),
    sa.Column('Segment', sa.REAL(), nullable=True),
    sa.Column('Trust_in_financial_deficit', sa.Text(), nullable=True),
    sa.Column('Rank', sa.REAL(), nullable=True),
    sa.Column('Likely_range_of_rank', sa.Text(), nullable=True)
    )

    op.create_table('consolidated',
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('treatment', sa.Text(), nullable=False),
    sa.Column('incomplete', sa.Integer(), nullable=True),
    sa.Column('incomplete_dta', sa.Integer(), nullable=True),
    sa.Column('admitted', sa.Integer(), nullable=True),
    sa.Column('new_periods', sa.Integer(), nullable=True),
    sa.Column('nonadmitted', sa.Integer(), nullable=True),
    sa.Column('incomplete_prev', sa.Integer(), nullable=True),
    sa.Column('incomplete_diff', sa.Integer(), nullable=True),
    sa.Column('incomplete_expected', sa.Integer(), nullable=True),
    sa.Column('untreated', sa.Integer(), nullable=True),
    sa.Column('admitted_prev', sa.Integer(), nullable=True),
    sa.Column('new_periods_prev', sa.Integer(), nullable=True),
    sa.Column('nonadmitted_prev', sa.Integer(), nullable=True),
    sa.Column('treated', sa.Integer(), nullable=True),
    sa.Column('treated_prev', sa.Integer(), nullable=True),
    sa.Column('wait_diff', sa.Integer(), nullable=True),
    sa.Column('wait_gte_18', sa.Integer(), nullable=True),
    sa.Column('wait_lt_18', sa.Integer(), nullable=True),
    sa.Column('wait_sum', sa.Integer(), nullable=True),
    sa.Column('wait_pct_lt_18', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider'], ['providers.provider_code'], ),
    sa.PrimaryKeyConstraint('period', 'provider', 'treatment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consolidated')
    op.drop_table('providers')
    op.drop_index('provider_Trust_code_uindex', table_name='provider')
    op.drop_table('provider')
    # ### end Alembic commands ###
