"""initial schemajhbugefe

Revision ID: 896b6cc92d2f
Revises: cdabe9db131d
Create Date: 2025-12-07 15:11:58.831123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896b6cc92d2f'
down_revision: Union[str, Sequence[str], None] = 'cdabe9db131d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admitted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qa_wait_diff', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admitted', schema=None) as batch_op:
        batch_op.drop_column('qa_wait_diff')

    # ### end Alembic commands ###
