"""initial schema

Revision ID: 8aadb59c0c96
Revises: 6bcd6014e3b3
Create Date: 2025-10-26 03:18:17.885919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aadb59c0c96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_rtt',
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('provider_org_code', sa.Text(), nullable=False),
    sa.Column('rtt_part_type', sa.Text(), nullable=False),
    sa.Column('treatment_function_code', sa.Text(), nullable=False),
    sa.Column('gt_00_to_01_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_01_to_02_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_02_to_03_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_03_to_04_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_04_to_05_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_05_to_06_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_06_to_07_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_07_to_08_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_08_to_09_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_09_to_10_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_10_to_11_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_11_to_12_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_12_to_13_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_13_to_14_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_14_to_15_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_15_to_16_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_16_to_17_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_17_to_18_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_18_to_19_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_19_to_20_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_20_to_21_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_21_to_22_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_22_to_23_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_23_to_24_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_24_to_25_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_25_to_26_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_26_to_27_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_27_to_28_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_28_to_29_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_29_to_30_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_30_to_31_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_31_to_32_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_32_to_33_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_33_to_34_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_34_to_35_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_35_to_36_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_36_to_37_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_37_to_38_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_38_to_39_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_39_to_40_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_40_to_41_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_41_to_42_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_42_to_43_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_43_to_44_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_44_to_45_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_45_to_46_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_46_to_47_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_47_to_48_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_48_to_49_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_49_to_50_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_50_to_51_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_51_to_52_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_52_to_53_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_53_to_54_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_54_to_55_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_55_to_56_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_56_to_57_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_57_to_58_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_58_to_59_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_59_to_60_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_60_to_61_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_61_to_62_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_62_to_63_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_63_to_64_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_64_to_65_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_65_to_66_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_66_to_67_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_67_to_68_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_68_to_69_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_69_to_70_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_70_to_71_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_71_to_72_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_72_to_73_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_73_to_74_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_74_to_75_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_75_to_76_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_76_to_77_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_77_to_78_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_78_to_79_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_79_to_80_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_80_to_81_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_81_to_82_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_82_to_83_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_83_to_84_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_84_to_85_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_85_to_86_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_86_to_87_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_87_to_88_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_88_to_89_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_89_to_90_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_90_to_91_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_91_to_92_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_92_to_93_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_93_to_94_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_94_to_95_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_95_to_96_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_96_to_97_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_97_to_98_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_98_to_99_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_99_to_100_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_100_to_101_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_101_to_102_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_102_to_103_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_103_to_104_weeks', sa.Integer(), nullable=True),
    sa.Column('gt_104_weeks', sa.Integer(), nullable=True),
    sa.Column('patients_with_unknown_clock_start_date', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('total_all', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('period', 'provider_org_code', 'rtt_part_type', 'treatment_function_code')
    )
    op.create_table('outpatients_activity',
    sa.Column('reporting_period', sa.Text(), nullable=False),
    sa.Column('geography_level', sa.Text(), nullable=False),
    sa.Column('organisation_code', sa.Text(), nullable=False),
    sa.Column('measure_type', sa.Text(), nullable=False),
    sa.Column('measure', sa.Text(), nullable=False),
    sa.Column('measure_value', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('reporting_period', 'geography_level', 'organisation_code', 'measure_type', 'measure')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outpatients_activity')
    op.drop_table('all_rtt')
    # ### end Alembic commands ###
