"""initial schemajhbug

Revision ID: cdabe9db131d
Revises: c750d7401492
Create Date: 2025-12-07 15:10:11.695672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdabe9db131d'
down_revision: Union[str, Sequence[str], None] = 'c750d7401492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admitted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qa_wait_sum', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qa_diff_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qa_diff_total_all', sa.Integer(), nullable=True))
        batch_op.drop_column('wait_sum')
        batch_op.drop_column('diff_total_all')
        batch_op.drop_column('diff_total')

    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.alter_column('Trust_code',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.alter_column('Trust_code',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('admitted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diff_total', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('diff_total_all', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('wait_sum', sa.INTEGER(), nullable=True))
        batch_op.drop_column('qa_diff_total_all')
        batch_op.drop_column('qa_diff_total')
        batch_op.drop_column('qa_wait_sum')

    # ### end Alembic commands ###
